### ISSUE TITLE
Initial Implementation of Basic Functionality

### ISSUE THREAD

**Issue by habodoni** [habodoni/productivity-pal#1]
### Summary
Implemented the foundational components for the Productivity Pal project. This includes basic functionality for user interaction, workflow switching, and productivity analysis.

### Completed Features
- **Workflow Switching**:
  - Allows users to switch between predefined workflow modes, such as "Focus Mode."
  - Example Output: `Switched to focus mode with apps: Notion, Slack`.
- **Productivity Analysis**:
  - Notifies the user when no productivity data is available for analysis.
  - Example Output: `No data to analyze.`
- **Basic User Interface**:
  - Accepts user input via the terminal and provides responses.

### Tasks Completed
- [x] Created `WorkflowManager` class with a `switch_mode` method.
- [x] Created `AnalyticsEngine` class with placeholder functionality for productivity analysis.
- [x] Created `UserInterface` class for command handling.

### Output Example
```text
Welcome to Productivity Pal!
Enter a command (e.g., 'focus mode', 'analyze productivity'): focus mode
Switched to focus mode with apps: Notion, Slack
Enter a command (e.g., 'focus mode', 'analyze productivity'): analyze productivity
No data to analyze.
